#######################################################
# 
# dressageFactory.py
# Python implementation of the Class dressageFactory
# Generated by Enterprise Architect
# Created on:      25-f�vr.-2026 14:56:32
# Original author: HP
# 
#######################################################
from models.dresseur import Dresseur
from factories.profilFactory import ProfilFactory


class DressageFactory(ProfilFactory):

    def creer_profil(self, *args, **kwargs):
        return Dresseur(*args, **kwargs)


   

