#######################################################
# 
# dressageFactory.py
# Python implementation of the Class dressageFactory
# Generated by Enterprise Architect
# Created on:      25-f�vr.-2026 14:56:32
# Original author: HP
# 
#######################################################
from factories.profilFactory import ProfilFactory
from abc import ABC, abstractmethod

class dressageFactory(ProfilFactory):
    ProfilFactory= ProfilFactory()
    def creer_profil():
        pass


   

