#######################################################
# 
# GardeServiceFactory.py
# Python implementation of the Class GardeServiceFactory
# Generated by Enterprise Architect
# Created on:      22-f�vr.-2026 23:25:18
# Original author: HP
# 
#######################################################
from services import serviceAnimalier
import serviceFactory

class GardeServiceFactory(serviceFactory):
    def creer_service():
        pass

    
    
