#######################################################
# 
# gardeFactory.py
# Python implementation of the Class gardeFactory
# Generated by Enterprise Architect
# Created on:      25-f�vr.-2026 14:56:37
# Original author: HP
# 
#######################################################
from factories.profilFactory import ProfilFactory
from abc import ABC, abstractmethod

class GardeFactory(ProfilFactory):
   
    def creer_profil():
        pass

    


    
