#######################################################
# 
# NourritureServiceFactory.py
# Python implementation of the Class NourritureServiceFactory
# Generated by Enterprise Architect
# Created on:      22-f�vr.-2026 23:25:24
# Original author: HP
# 
#######################################################

import serviceFactory
from services import serviceAnimalier

class NourritureServiceFactory(serviceFactory):
    def creer_service():
        pass
