#######################################################
# 
# ProfilFactory.py
# Python implementation of the Class ProfilFactory
# Generated by Enterprise Architect
# Created on:      25-f�vr.-2026 14:56:45
# Original author: HP
# 
#######################################################
import factories.profilFactory as profilFactory
from abc import ABC, abstractmethod

class ProfilFactory(ABC):
    @abstractmethod
    def creer_profil():
        pass