#######################################################
# 
# serviceFactory.py
# Python implementation of the Interface serviceFactory
# Generated by Enterprise Architect
# Created on:      23-f�vr.-2026 01:37:04
# Original author: HP
# 
#######################################################
from services import serviceAnimalier
from abc import ABC, abstractmethod

class ServiceFactory(ABC):
    @abstractmethod
    def creer_service(self, id_service: int, prix: float) -> serviceAnimalier:
        pass