#######################################################
# 
# ToilettageServicefACTORY.py
# Python implementation of the Class ToilettageServicefACTORY
# Generated by Enterprise Architect
# Created on:      22-f�vr.-2026 23:25:26
# Original author: HP
# 
#######################################################
from services import serviceAnimalier
import serviceFactory

class ToilettageServicefACTORY(serviceFactory):
    

    def creer_service():
        pass
