#######################################################
# 
# veterinaireFactory.py
# Python implementation of the Class veterinaireFactory
# Generated by Enterprise Architect
# Created on:      25-f�vr.-2026 14:56:51
# Original author: HP
# 
#######################################################
from factories.profilFactory import ProfilFactory
from abc import ABC, abstractmethod

class VeterinairieFactory(ProfilFactory):
    ProfilFactory= ProfilFactory()
    def creer_profil():
        pass
