#######################################################
# 
# VeterinaireServiceFactory.py
# Python implementation of the Class VeterinaireServiceFactory
# Generated by Enterprise Architect
# Created on:      22-f�vr.-2026 23:25:30
# Original author: HP
# 
#######################################################

import serviceFactory
from services import serviceAnimalier

class VeterinaireServiceFactory(serviceFactory):
    def creer_service(self, id_service: int, prix: float) -> serviceAnimalier:
        pass