#######################################################
# 
# veterinaireFactory.py
# Python implementation of the Class veterinaireFactory
# Generated by Enterprise Architect
# Created on:      25-f�vr.-2026 14:56:51
# Original author: HP
# 
#######################################################
from models.veterinaire import Veterinaire
from factories.profilFactory import ProfilFactory


class VeterinaireFactory(ProfilFactory):

    def creer_profil(self, *args, **kwargs):
        return Veterinaire(*args, **kwargs)
    