#######################################################
# 
# LoggerSingleton.py
# Python implementation of the Class LoggerSingleton
# Generated by Enterprise Architect
# Created on:      25-f�vr.-2026 23:07:34
# Original author: HP
# 
#######################################################
class Logger_config:
    _instance = None
    def ____init__():
        pass

    def getInstance():
        pass

    def log(message):
        pass