#######################################################
# 
# LoggerSingleton.py
# Python implementation of the Class LoggerSingleton
# Generated by Enterprise Architect
# Created on:      23-f�vr.-2026 11:19:50
# Original author: HP
# 
#######################################################
import ConfigurationPlateforme

class LoggerSingleton:
    def ____init__():
        pass

    def getInstance():
        pass

    def log(message):
        pass