#######################################################
# 
# demandeService.py
# Python implementation of the Class demandeService
# Generated by Enterprise Architect
# Created on:      23-f�vr.-2026 01:37:04
# Original author: HP
# 
#######################################################
from serviceAnimalier import serviceAnimalier
from prestationService import prestationService
from models import Fournisseur

class demandeService:
    m_prestationService= prestationService()

    m_Fournisseur= Fournisseur()

    m_serviceAnimalier= serviceAnimalier()
