#######################################################
# 
# gardeService.py
# Python implementation of the Class gardeService
# Generated by Enterprise Architect
# Created on:      23-f�vr.-2026 01:37:04
# Original author: HP
# 
#######################################################
import serviceAnimalier

class gardeService(serviceAnimalier):
    def calculer_prix(self) -> float:
        base = self.prix_base
        total = base * (1 + self.taux_tva + self.taux_commission)
        return total