#######################################################
# 
# nourritureService.py
# Python implementation of the Class nourritureService
# Generated by Enterprise Architect
# Created on:      23-f�vr.-2026 01:37:04
# Original author: HP
# 
#######################################################
import serviceAnimalier

class nourritureService(serviceAnimalier):
    def payer():
        pass