#######################################################
# 
# gardeService.py
# Python implementation of the Class gardeService
# Generated by Enterprise Architect
# Created on:      23-f�vr.-2026 01:37:04
# Original author: HP
# 
#######################################################

from models.prestation_garde import PrestationGarde

class Prestation_garde_Services:

    @staticmethod
    def creer_prestation(garde, data, session):
          prestation = PrestationGarde(
            garde_id=garde.id,
            **data
        )
    session.add(prestation)
    session.commit()
    return prestation