#######################################################
# 
# prestationService.py
# Python implementation of the Class prestationService
# Generated by Enterprise Architect
# Created on:      23-f�vr.-2026 01:37:04
# Original author: HP
# 
#######################################################
from models import methodePaiement ,Evaluation
import serviceAnimalier

class prestationService:
    m_serviceAnimalier= serviceAnimalier()

    def __confirmerServiceTermine():
        pass

    def __annulerRetournerViaRelais():
        pass

    