#######################################################
# 
# dressageService.py
# Python implementation of the Class dressageService
# Generated by Enterprise Architect
# Created on:      22-f�vr.-2026 20:46:19
# Original author: HP
# 
#######################################################
import services.profilAnimalier as profilAnimalier

class DressageService(profilAnimalier):
    def payer():
        pass