#######################################################
# 
# serviceAnimalier.py
# Python implementation of the Class serviceAnimalier
# Generated by Enterprise Architect
# Created on:      23-f�vr.-2026 01:37:04
# Original author: HP
# 
#######################################################


class serviceAnimalier:
    __tauxTva = 0.05
    __tauxCommision = 0.15
    def demander():
        pass

    def accepter():
        pass

    def demarrer():
        pass

    def terminer():
        pass

    def calculerPrix():
        pass