#######################################################
# 
# statutService.py
# Python implementation of the Enumeration statutService
# Generated by Enterprise Architect
# Created on:      23-févr.-2026 01:37:05
# Original author: HP
# 
#######################################################


class statutService:
    pass