#######################################################
# 
# toilettageService.py
# Python implementation of the Class toilettageService
# Generated by Enterprise Architect
# Created on:      22-f�vr.-2026 20:46:20
# Original author: HP
# 
#######################################################
import serviceAnimalier

class toilettageService(serviceAnimalier):
    def payer():
        pass