#######################################################
# 
# veterinaireService.py
# Python implementation of the Class veterinaireService
# Generated by Enterprise Architect
# Created on:      23-f�vr.-2026 01:37:05
# Original author: HP
# 
#######################################################
import serviceAnimalier

class veterinaireService(serviceAnimalier):
    def payer():
        pass