#######################################################
# 
# administrateur.py
# Python implementation of the Class administrateur
# Generated by Enterprise Architect
# Created on:      25-f�vr.-2026 15:00:54
# Original author: HP
# 
#######################################################
from models.utilisateur import Utilisateur
from models.veterinaire import veterinaire
from models.dresseur import Dresseur
from models.garde import Garde
import models.client
import mysql.connector


def get_connection():
    return mysql.connector.connect(
        host="localhost",
        user="ton_user",
        password="ton_mdp",
        database="nom_de_ta_base"
    )


class administrateur(Utilisateur):
    def __init__(self, id_utilisateur: int, nom: str, prenom: str, email: str, mot_de_passe: str, role: str, telephone: str):
        super().__init__(id_utilisateur, nom, prenom, email, mot_de_passe, role, telephone)

    veterinaire= veterinaire()
    dresseur= Dresseur()

    def ajouter_profil():
        def ajouter_profil(self, table_profil, data: dict):
        #table_profil: "dresseurs", "gardes", "veterinaires"#
        #data: dict avec colonnes et valeurs#

            cols = ", ".join(data.keys())
            vals = ", ".join([f"'{v}'" for v in data.values()])
            sql = f"INSERT INTO {table_profil} ({cols}) VALUES ({vals})"

        conn = get_connection()
        cursor = conn.cursor()
        cursor.execute(sql)
        conn.commit()
        cursor.close()
        conn.close()


    def supprimer_profil(self, table_profil, profil_id):

        sql = f"DELETE FROM {table_profil} WHERE id = {profil_id}"
        conn = get_connection()
        cursor = conn.cursor()
        cursor.execute(sql)
        conn.commit()
        cursor.close()
        conn.close()

    def modifier_profil(self, table_profil, profil_id, data: dict):

        set_clause = ", ".join([f"{k}='{v}'" for k, v in data.items()])
        sql = f"UPDATE {table_profil} SET {set_clause} WHERE id = {profil_id}"
        conn = get_connection()
        cursor = conn.cursor()
        cursor.execute(sql)
        conn.commit()
        cursor.close()
        conn.close()

    def consulter_profil(self):
        tables = ["veterinaires", "dresseurs", "gardes"]
        result = {}
        conn = get_connection()
        cursor = conn.cursor(dictionary=True)
        for table in tables:
            cursor.execute(f"SELECT * FROM {table}")
            result[table] = cursor.fetchall()
        cursor.close()
        conn.close()
        return result

    def voir_clients_inscrits(self):
        tables = ["prestation_veterinaire", "prestation_dressage", "prestation_garde"]
        clients_ids = set()
        conn = get_connection()
        cursor = conn.cursor()
        for table in tables:
            cursor.execute(f"SELECT client_id FROM {table}")
            for (cid,) in cursor.fetchall():
                clients_ids.add(cid)
        cursor.close()
        conn.close()
        return list(clients_ids)

    def voir_dashboard(self):
        """
        Exemple simple de stats :
        - nb total de profils par type
        - nb total de prestations
        """
        conn = get_connection()
        cursor = conn.cursor()

        stats = {}
        for table in ["veterinaires", "dresseurs", "gardes"]:
            cursor.execute(f"SELECT COUNT(*) FROM {table}")
            stats[table] = cursor.fetchone()[0]

        for table in ["prestation_veterinaire", "prestation_dressage", "prestation_garde"]:
            cursor.execute(f"SELECT COUNT(*) FROM {table}")
            stats[table] = cursor.fetchone()[0]

        cursor.close()
        conn.close()
        return stats

    def consulter_revenus_profils_percus(self):
        """
        Exemple : total des abonnements actifs
        """
        sql = "SELECT SUM(montant) FROM abonnement WHERE statut='ACTIF'"
        conn = get_connection()
        cursor = conn.cursor()
        cursor.execute(sql)
        total = cursor.fetchone()[0] or 0
        cursor.close()
        conn.close()
        return total