#######################################################
# 
# administrateur.py
# Python implementation of the Class administrateur
# Generated by Enterprise Architect
# Created on:      23-f�vr.-2026 01:37:04
# Original author: HP
# 
#######################################################
import models.Utilisateur as Utilisateur
import Fournisseur

class Administrateur(Utilisateur):
    def __init__(self, id_utilisateur: int, nom: str, prenom: str, email: str, mot_de_passe: str, role: str, telephone: str):
        super().__init__(id_utilisateur, nom, prenom, email, mot_de_passe, role, telephone)
    m_Fournisseur= Fournisseur()










    def __ajouterFournisseur():
        pass

    def __supprimerFournisseur():
        pass

    def __modifierFournisseur():
        pass

    def __consulterFournisseur():
        pass

    def __voirBenefciairesInscrits():
        pass

    def __voirDashboard():
        pass

    def __consulterRevenusPerçus():
        pass