#######################################################
# 
# beneficiare.py
# Python implementation of the Class beneficiaire
# Generated by Enterprise Architect
# Created on:      23-f�vr.-2026 01:37:04
# Original author: HP
# 
#######################################################
import models.Utilisateur as Utilisateur
from services import demandeService

class Client(Utilisateur):
    def __init__(self, id_utilisateur: int, nom: str, prenom: str, email: str, mot_de_passe: str, role: str, telephone: str, adresse: str):
        super().__init__(id_utilisateur, nom, prenom, email, mot_de_passe, role, telephone)
        self.__adresse = adresse
    m_demandeService= demandeService()










    def voirServiceDisponible():
        pass

    def __demanderService():
        pass

    def __payerService():
        pass
    def voirServiceDisponible():
        pass