#######################################################
# 
# client.py
# Python implementation of the Class client
# Generated by Enterprise Architect
# Created on:      25-f�vr.-2026 15:03:54
# Original author: HP
# 
#######################################################
from models.utilisateur import Utilisateur


class Client(Utilisateur):

    def afficher_infos(self):
        return f"Client: {self.nom} {self.prenom}"