from enum import Enum


class TypeService(Enum):
    GARDESERVICE = "GARDESERVICE"
    DRESSAGESERVICE = "DRESSAGESERVICE"
    VETINAIRESERVICE = "VETINAIRESERVICE"
    TOILETTAGESERVICE = "TOILETTAGESERVICE"
    NOURRISSEMENTSERVICE = "NOURRISSEMENTSERVICE"

class StatutPrestation(Enum):
    EN_ATTENTE = "EN_ATTENTE"
    EN_COURS = "EN_COURS"
    TERMINE = "TERMINE"
    ANNULE = "ANNULE"
    REFUSEE = "REFUSEE"

class MethodePaiment(Enum):
    CARTE_BANCAIRE = "CARTE_BANCAIRE"
    VIREMENT = "VIREMENT"
    ESPÈCES = "ESPÈCES" 
   

class statutPaiement(Enum):
    EN_ATTENTE = "EN_ATTENTE"
    EN_COURS = "EN_COURS"
    REFUSEE = "REFUSEE"
    PAYEE = "PAYEE"