#######################################################
# 
# statutAbonnement.py
# Python implementation of the Enumeration statutAbonnement
# Generated by Enterprise Architect
# Created on:      25-f�vr.-2026 14:56:48
# Original author: HP
# 
#######################################################
from enum import Enum

class statutAbonnement(Enum):
    PAYE_ACTIF= "PAYE_ACTIF"
    NON_PAYE_INACTIF= "NON_PAYE_INACTIF"

class statutPrestation(Enum):
    PLANIFIEE= "PLANIFIEE"
    EN_COURS= "EN_COURS"
    TRMINEE= "TRMINEE"

class statutRole((Enum)):
    ADMINISTRATEUR= "ADMINISTRATEUR"
    PROFIL= "PROFIL"
    CLIENT= "CLIENT"

class disponibilite(Enum):
    DISPONIBLE = "DISPONIBLE"
    INDISPONIBLE = "INDISPONIBLE"

class TypeService(Enum):
    DRESSAGE = "DRESSAGE"
    GARDE = "GARDE"
    VETERINAIRE = "VETERINAIRE"