#######################################################
# 
# Fournisseur.py
# Python implementation of the Class Fournisseur
# Generated by Enterprise Architect
# Created on:      22-f�vr.-2026 20:46:19
# Original author: HP
# 
#######################################################
import Utilisateur
from services import serviceAnimalier

class Fournisseur(Utilisateur):
    def __init__(self, id_utilisateur: int, nom: str, prenom: str, email: str, mot_de_passe: str, role: str, telephone: str, raison_sociale: str, note_moyenne: str, disponibilite: str, adresse: str):
        super().__init__(id_utilisateur, nom, prenom, email, mot_de_passe, role, telephone)
        self.__raison_sociale = raison_sociale
        self.__note_moyenne = note_moyenne
        self.__disponibilite = disponibilite
        self.__adresse = adresse
    reoit= serviceAnimalier()

    def recevoirNotification():
        pass

    def accepterDemande():
        pass

    def refuserDemande():
        pass

    def declarerServiceTermine():
        pass

    def consulterHistorique():
        pass

    def voirRevenus():
        pass
    
    def creerService():
        pass