#######################################################
# 
# User.py
# Python implementation of the Class Utilisateur
# Generated by Enterprise Architect
# Created on:      23-f�vr.-2026 01:37:05
# Original author: HP
# 
#######################################################
import enum

class Role(enum.Enum):
    ADMIN = "admin"
    CLIENT = "client"
    VETERINAIRE = "veterinaire"
    GARDE = "garde"


class Utilisateur():
        
        def __init__(self, id_utilisateur: int, nom: str, prenom: str, email: str, mot_de_passe: str, role: Role, telephone: str):
            self.__id_utilisateur = id_utilisateur
            self.nom = nom
            self.__prenom = prenom
            self.__email = email
            self.__mot_de_passe = mot_de_passe
            self.__role = role
            self.__telephone = telephone
            pass